apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-build
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-build
    app.kubernetes.io/part-of: demo-build
  name: demo-build
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: demo-build
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: demo-build
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/otikhomi-tenant/demo-build/demo-build@sha256:b89c3187df9cb668e07825e75ae340a7b7b3285c36caa4060a0e4188f9aea144
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
